spring:
  messages:
    basename: i18n/login

  thymeleaf:
    cache: false

  security:
    user:
      name: user
      password: 123

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf8
    username: root
    password: root

  mail:
    host: smtp.qq.com
    username: 3189699338@qq.com
    password: bbb
    default-encoding: UTF-8

  redis:
    database: 0
    host: localhost
    port: 6379
    password: 123456
    jedis:
      pool:
        max-active: 10
        max-wait: -1
    timeout: 500

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: swjtu.syyymq.entity
  configuration:
    map-underscore-to-camel-case: true

mail:
  fromMail:
    sender: 3189699338@qq.com
    expiredTime: 3
